### ISSUE TITLE
Update: gazebo RGV behavior

### ISSUE THREAD

**Issue by nipe1783** [nipe1783/ATTACKS-SW#32]
Currently, the gazebo RGVs move randomly at speeds of up to 2 m/s, but they do not stop for periods of 90 seconds. It is necessary to enable the RGVs to come to a complete stop and then resume movement. (This might be difficult since I am simulating the RGVs as obstacles and not a separate agent.)

Deliverables:

- [ ] RGVs move around the environment and randomly come to a stop for 90 seconds before moving again.

**Comment by aiba4531** [comment]
Look into objects in Gazebo creating a object that can follow logic and subsequently at more realistic path.
